### ISSUE TITLE
As a project coordinator I want to easily view and filter metrics for measuring impact.

### ISSUE THREAD

**Issue by Oba-One** [greenpill-dev-guild/impact-framework-backend#34]
# Done State

- [ ] greenpill-dev-guild/impact-framework#4
- [ ] greenpill-dev-guild/impact-framework#5
- [ ] greenpill-dev-guild/impact-framework#6
- [ ] greenpill-dev-guild/impact-framework#7

# Technical Requirements

- Design follow guideline outlined in [PRD](https://app.charmverse.io/impact-visualization/impact-evaluation-prd-9030869483317048)
- Typescript used for React components
- Storybook used for creating components
- Database is protected against attack with light authentication

# Resources

- [Figma Designs](https://www.figma.com/file/T9gqqMmCGQFZHppwvAJW8G/Designs?type=design&node-id=4149-12292&mode=design)
